# Sidekiq configuration
# https://github.com/sidekiq/sidekiq/wiki/Advanced-Options

:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>

:queues:
  - [critical, 3]
  - [default, 2]
  - [mailers, 2]
  - [low, 1]

# Limit retries for failed jobs
:max_retries: 3

